### PR TITLE
Avoid NPE if get() is never called before close()

### PR DESCRIPTION
**Pull request by garricko**

### CODE REVIEW

**Review by jpallas — COMMENTED** [review]
After thinking about this some more, I recommend reverting my earlier change.  I suspect the path that brought me to that point was misguided. 

I would consider removing `txStarted` completely; unless I'm mistaken it is always `connection != null`.

**Comment by garricko** [comment]
Ok, I reverted the earlier commit and removed the flag as suggested. I will keep the new null check in close() anyway just for defensive purposes.

**Comment by jpallas** [comment]
Did you want to make the txStarted change to DatabaseProviderVertx?  I overlooked it when I made the original change (oops).

**Comment by garricko** [comment]
Applied similar changes for Vertx and added a test in case we attempt similar shenanigans again.

**Review by jpallas — APPROVED** [review]
Looks good.  Thanks.

**Pull request merged**
